### ISSUE TITLE
Glitches at zero-crossings of waveforms on DAC?

### ISSUE THREAD

**Issue by endolith** [PaulStoffregen/Audio#111]
Not sure if this is an off-by-one bug or hardware imperfection or what, but I see positive spikes at the zero-crossings of synth waveforms when running through the DAC, but not when running through the CODEC board. Simple example:

```
#include <Audio.h>
#include <Wire.h>
#include <SPI.h>
#include <SD.h>

AudioSynthWaveform   waveform;
AudioOutputAnalog    audioOutput;
AudioConnection patchCord3(waveform, 0, audioOutput, 0);

void setup() {
  AudioMemory(12);
  waveform.begin(0.1, 1000, WAVEFORM_TRIANGLE);  // wave with glitches
//  waveform.begin(0.001, 1000, WAVEFORM_TRIANGLE);  // shows only glitches
//  waveform.begin(0, 1000, WAVEFORM_TRIANGLE);  // no glitches
}

void loop() {
}
```

At full amplitude they're not visible:

![newfile0](https://cloud.githubusercontent.com/assets/58611/6861474/385069f0-d40d-11e4-8120-62df19d745a2.png)

but at 0.1 they are:
![newfile2](https://cloud.githubusercontent.com/assets/58611/6861477/43c48910-d40d-11e4-9712-c1d7b6fe48ba.png)
![newfile3](https://cloud.githubusercontent.com/assets/58611/6861478/43c63788-d40d-11e4-895c-bc1717867a55.png)
![newfile1](https://cloud.githubusercontent.com/assets/58611/6861479/43cb6eec-d40d-11e4-99d2-84aa12bad343.png)

![img_20150326_215105](https://cloud.githubusercontent.com/assets/58611/6861704/e9c74188-d410-11e4-8dfe-79746c485abd.jpg)

with external CODEC I don't see any, even at 0.1 amplitude:
![newfile4](https://cloud.githubusercontent.com/assets/58611/6861486/4f438480-d40d-11e4-8724-1469060ab9d2.png)

**Comment by Nantonos** [comment]
Nicely done report. So you are seeing these on two waveforms (ramp and triangle) and on both rising and falling slopes. most severe at zero crossing but also lesser spikes elsewhere. The external codec is the SGTL5000 audio board?

As you have no reconstruction filter, I wonder if this is aliasing, or sampling frequency breakthrough. Does varying the frequency of the waveform change the glitch pattern at all?

This could be a MSB DAC glitch though. The datasheet is not as detailed here as one would expect for an external DAC chip, for example.

**Comment by endolith** [comment]
It was on sine also, I'm not sure about square, I didn't look closely at the zero crossings.

> The external codec is the SGTL5000 audio board?

Yes, [this board](https://www.pjrc.com/store/teensy3_audio.html)

> Does varying the frequency of the waveform change the glitch pattern at all?

No, it was always around zero crossings, no matter what frequency.  I guess I didn't check extremely low or high frequencies, though, only around 1-4 kHz.  Also I couldn't figure out which frequency would make the spikes a stable distance apart; period would vary by ±1 sample

**Comment by PaulStoffregen** [comment]
Yup, running the code and I see it here too:

![file](https://cloud.githubusercontent.com/assets/965463/6877966/eead33f0-d493-11e4-8130-ad345a683c33.png)

**Comment by PaulStoffregen** [comment]
I'm afraid this may simply be a hardware limitation that requires external analog filtering.  Maybe?

Here's a zoom in to just 1 spike.  It's barely 1 us wide, much less than the 22.7 us period where a new value is being written to the DAC register.

![file2](https://cloud.githubusercontent.com/assets/965463/6878015/8c6a2918-d494-11e4-8b22-2072806ceef9.png)

**Comment by endolith** [comment]
They're still present with the scope's digital filter at 20 kHz, though, so part of it is in the audio band already:

![20 khz filter](https://cloud.githubusercontent.com/assets/58611/6879467/71ffb024-d4cc-11e4-8603-bd72cf3b3e67.png)

with the scope's "Peak Detect" mode, they show up on every cycle, and there are smaller ones at different amplitudes that are the same every cycle:

1 Hz, 0.1 amplitude:
![peak detect 1 hz](https://cloud.githubusercontent.com/assets/58611/6879476/d8135a46-d4cc-11e4-8fed-5a0ae3036d37.png)

![1 hz peak detect](https://cloud.githubusercontent.com/assets/58611/6879498/d83b71ba-d4cd-11e4-9046-34f28471e8da.png)

1 Hz, 1 amplitude:
![1 hz](https://cloud.githubusercontent.com/assets/58611/6879478/eac3cb30-d4cc-11e4-8047-0e7a5ab3c673.png)

**Comment by Nantonos** [comment]
Yes, this looks like a "major carry transition glitch".
http://e2e.ti.com/blogs_/b/analogwire/archive/2013/06/14/what-s-with-all-this-glitch-ing
http://www.maximintegrated.com/en/app-notes/index.mvp/id/583
http://digital.ni.com/public.nsf/allkb/9B13E25B0B0EC197862562B4007D2E33

There is also a lot of high-frequency hash on top of the waveform. The K20P64M72SF1 datasheet is entirely silent on the matter of glitch energy. It does suggest a 47pF cap at the output.

Comparison of the triangle produced by the sketch at the head of this post (1kHz triangle) with that produced by an analog oscillator (Intellijel Dixie II):
![teensy3 1_dac-1k-tri](https://cloud.githubusercontent.com/assets/2506926/6881178/bcbca616-d554-11e4-810b-50fa62b0bf53.png)
![dixie-1k-tri](https://cloud.githubusercontent.com/assets/2506926/6881179/c26d3134-d554-11e4-8691-71ac14f4c6bf.png)

**Comment by endolith** [comment]
yes, that looks like it.  so it's not a bug, just a hardware limitation.
