### ISSUE TITLE
GUI documentation URLs are broken

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#140]
Recent changes seem to have broken the URL updating to append the currently selected documentation.

Here's the original commit which added this feature: https://github.com/PaulStoffregen/Audio/commit/029bbe268f5ec26d7d3cb88a2421ef601f5a053f

This URL update allows people to copy the URL from the address bar into a forum or email message, when they wish to answer a question with a link to specific documentation.

**Comment by mamuesp** [comment]
The function selectNode carries the lines which are responsible for this functionality. They had be turned into a comment in the version which is base of my fork. So it was set off already by yourself before the fork. I reactivated it now, with the next commit, all will be fine.

**Comment by mamuesp** [comment]
Done.

**Comment by mamuesp** [comment]
I found the reason why these two lines had been commented out: http://bit.ly/1NZ5Zuu
