### ISSUE TITLE
Audio/Keywords.txt needs AudioAnalyzeNoteFrequency

### ISSUE THREAD

**Issue by StevenLCox** [PaulStoffregen/Audio#146]
AudioAnalyzeNoteFrequency should replace AudioAnalyzeGuitarTuner in the Audio library keywords.txt. https://github.com/PaulStoffregen/Audio/blob/master/keywords.txt

Note: This is my first GitHub Issue. Paul, Thanks so much for the Audio Workshop video and of course all the Teensy products. I'm working through some audio projects with my 15 year old son and the Audio Board is a great resource!
Steve

**Comment by PaulStoffregen** [comment]
Thanks.
