### ISSUE TITLE
sd card error

### ISSUE THREAD

**Issue by gorkemturhan** [PaulStoffregen/Audio#174]
hello . ı have a problem. ı try to play a sound file with teensy.  but when ı download  part_1_03_Playing_Music   there is a mistake that is   " Unable to access the SD card "    .  ı also  have formated  sd card.   but problem continues .  can you help me ?

**Comment by PaulStoffregen** [comment]
Post here for support.
https://forum.pjrc.com/forums/3-Technical-Support-amp-Questions

This issue tracker is only for reporting bugs in the code itself (which is known to work in this case)
