### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by jeroendoggen** [PaulStoffregen/Audio#178]
The repository has no LICENSE file specifying the usage terms of the project. (MIT?, LGPL?, BSD?)

Normally, no license stated means "copyrighted" with no possibility to re-use the code in derived/other projects. That is probably not what all the current co-authors want.

**Comment by PaulStoffregen** [comment]
Every file has MIT license

**Comment by ell1e** [comment]
Why not add a `LICENSE.md` then? I just came to the repository with the same question, and it's kind of difficult to find out. Also, MIT usually is interpreted as requiring credit, so knowing the exact author/copyright line to put into credits would be quite useful.
