### ISSUE TITLE
GUI: export generates bad code after remaning nodes

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#181]
https://forum.pjrc.com/threads/34657-Audio-tool-generation-bug-renaming-nodes

https://forum.pjrc.com/threads/34202-Audio-System-Design-Tool-Renaming-nodes-bug

**Comment by ccrome** [comment]
Just created a new pull request here with a patch that seems to work for me:

https://github.com/PaulStoffregen/Audio/pull/182

**Comment by PaulStoffregen** [comment]
Looks like it's fully fixed.  Thanks.  :)

**Comment by ccrome** [comment]
No problem.  Easy fix :-)
