### ISSUE TITLE
Is the Audio library and Audio adapter compatible with the Teensy 3.5?

### ISSUE THREAD

**Issue by The-Oracle** [PaulStoffregen/Audio#207]
Pinout wise it seems that the Teensy 3.5 should work with the Teensy audio adapter, however on the PJRC site, I do not see the Teensy 3.5 listed as compatible with the Audio library. Could someone please clarify this pairing as compatible or not compatible.

Thanks,
JB

**Comment by FrankBoesing** [comment]
Yes it is. Next time, please use the forum for questions.

Am 5. November 2016 20:08:23 MEZ, schrieb Jeremy Brown <notifications@github.com>:
>Pinout wise it seems that the Teensy 3.5 should work with the Teensy
>audio adapter, however on the PJRC site, I do not see the Teensy 3.5
>listed as compatible with the Audio library. Could someone please
>clarify this pairing as compatible or not compatible.
>
>Thanks,
>JB
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/Audio/issues/207

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PaulStoffregen** [comment]
readme and main web page have been updated.
