### ISSUE TITLE
Gui Bug, AudioFilterStateVariable can not edit node name 

### ISSUE THREAD

**Issue by wolkstein** [PaulStoffregen/Audio#237]
Hi,
on AudioFilterStateVariable it is not possible to edit the node name.
This is caused by an copy and paste error in index.html line 2940.
`<script type="text/x-red" data-template-name="AudioFilterFIR">`
must changed to
`<script type="text/x-red" data-template-name="AudioFilterStateVariable">`

AudioFilterFIR is OK and the script for edit AudioFilterFIR node popup 
this is already done in line 2879.

think this error is caused from copy and paste.
/g
wolke

**Comment by PaulStoffregen** [comment]
Fixed.  Thanks!  :)
