### ISSUE TITLE
Part_2_05_Simple_Delay does not work with Teensy Audio Kit

### ISSUE THREAD

**Issue by IrwinKwan** [PaulStoffregen/Audio#240]
The example, as printed, does not work - the microphone does not activate and the delay doesn't activate.

I was able to make it work by commenting out the Serial.begin(9600) line.

**Comment by cianphillips** [comment]
Thanks! I am experiencing the same exact issue. You just saved me hours of hair pulling.

**Comment by PaulStoffregen** [comment]
This problem has been fixed in Teensyduino 1.38-beta2.
