### ISSUE TITLE
Instantiating AudioPlaySdWav from a library.

### ISSUE THREAD

**Issue by Gronnesby** [PaulStoffregen/Audio#250]
Hi!
I've been trying to write a library for a teensy-based project I'm doing.
In the library I instantiate 6 `AudioPlaySdWav` objects to connect to a mixer,
this is so that I can play multiple audio streams on top of eachother.

When I try to instantiate the 6 objects, the constructor `AudioPlaySdWav()`
seems to halt. The `AudioPlaySdWav()` is instantiated within a `init()` method
of the class in the library (not the constructor):

```
    Serial.println("Setting up Audio Channels");
    _N_CHANNELS = 6;
    for (int i = 0; i < _N_CHANNELS; i++)
    {
        Serial.print("Setting up channel ");
        Serial.println(i);
        _CHANNELS[i] = AudioPlaySdWav(); // Stops here for some reason
        Serial.println("Connecting channel to mixer");
        AudioConnection(_CHANNELS[i], 0, _MIXER, i);
    }
```
It does not go past the first two prints.
Any ideas what might be causing it?

I am running this on a teensy 3.5, using the builtin SD card as the source (which is not initialized yet).
Everything is compiled through the `Arduino IDE` (gave up trying to compile everything by hand).
The Audio version is 1.3.

Thanks!

**Comment by PaulStoffregen** [comment]
Post this on the forum.  Github issues are only for reporting confirmed bugs.
