### ISSUE TITLE
AudioOutputUSB won't work standalone

### ISSUE THREAD

**Issue by dronus** [PaulStoffregen/Audio#251]
Just wiring a simple sine oscilator to an AudioOutputUSB delivers silence on the USB audio. 

Adding some other output (eg. AudioOutputAnalog) make the thing run. This will still work even if this node is not wired!

examples/HardwareTesting/WavFilePlayerUSB/WavFilePlayerUSB.ino uses an abitrary AudioOutputAnalog output too, so others alredy seem to have stumbled on this problem.

**Comment by PaulStoffregen** [comment]
Really, we need some way for more people to notice this in the documentation....

**Comment by dronus** [comment]
Ok, found the documentation.
