### ISSUE TITLE
Option for Stero PWM

### ISSUE THREAD

**Issue by curieos** [PaulStoffregen/Audio#310]
### Description
I would like to use a Teensy 3.2 as a stereo USB DAC. I plan to hook it up to a stereo class D amp from Adafruit to power the speakers, but as is I can only do mono. Can the code be modified to allow a user to select 2 compatible pins of their choosing for each channel? I would do it myself if I were more familiar with the code.

**Comment by PaulStoffregen** [comment]
Quick answer: use the DAC for 1 channel and PWM + low-pass filter for the other.

Longer answer: ask on the forum.  This issue tracker is for reporting bugs.  We discuss developing new stuff on the forum.
