### ISSUE TITLE
Envelope AR

### ISSUE THREAD

**Issue by danidev** [PaulStoffregen/Audio#314]
Hello,
I write here because I don't know where is the best place to do it...
I've written an envelope object like the one in the library but with only 2 stages: AR.
It just get the noteOn trigger and then go through attack and release phases with a re-trigger when a new note-on arrives.
I did it for my personal use (to develop a drum machine) but I will be very happy if someone find it useful.

Just give me instructions on how I can propose it.

cheers,
daniele

**Comment by FrankBoesing** [comment]
Please ask here: https://forum.pjrc.com/
Github is not for questions or help.
