### ISSUE TITLE
Teensy 4.0 support

### ISSUE THREAD

**Issue by asaeed** [PaulStoffregen/Audio#320]
Wondering how robust is this library when using a Teensy 4.0 with a Teensy 4.0 audio shield?
I noticed some recent commit messages adding some support, but it's not listed as officially supported hardware on https://www.pjrc.com/teensy/td_libs_Audio.html

Thanks and very excited to dive in using your awesome platform!

**Comment by FrankBoesing** [comment]
Please use the forum https://forum.pjrc.com.
Thank you.
This is not the right platform to ask questions.
