### ISSUE TITLE
Where is the source code for AudioInputUSB object?

### ISSUE THREAD

**Issue by hhaudio** [PaulStoffregen/Audio#344]
Hi, I am working on a project for which an understanding and possible modification of the low level function of the AudioInputUSB object would be very useful. 

I am looking for the source code for this object but it doesn't appear to be included in this repo. It is not among the files labeled input, and a search for 'usb' within the repo returns only example files and some files relation to git management and the design tool ui. 

Where can I find the source code for AudioInputUSB object?

**Comment by FrankBoesing** [comment]
https://github.com/PaulStoffregen/cores/blob/master/teensy4/usb_audio.cpp

**Comment by PaulStoffregen** [comment]
Or here if using Teensy 3.x: https://github.com/PaulStoffregen/cores/blob/master/teensy3/usb_audio.cpp

**Comment by h4yn0nnym0u5e** [comment]
Answered, so can be closed
