### ISSUE TITLE
GUI assigns wrong instance names on copy-n-paste of objects

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#56]

**Comment by BleepLabs** [comment]
I've found the format for importing nodes but there are some issues.

`[{"id":"i2s2","type":"AudioOutputI2S","x":2105,"y":176,"z":0,"wires":[]},{"id":"i2s1","type":"AudioInputI2S","x":133,"y":176,"z":0,"wires":[["mixer1:0"],[]]},{"id":"i2s2","type":"AudioOutputI2S","x":489,"y":158,"z":0,"wires":[]},{"id":"mixer1","type":"AudioMixer4","x":311,"y":181,"z":0,"wires":[["i2s2:0"]]}]
`

Changing the end of that string to `...i2s2:0"]]},0`  doesn't turn off random naming as the [import nodes function](https://github.com/PaulStoffregen/Audio/blob/b3b3f857a89693d11860ac3c9d3782fd00bf010b/gui/red/nodes.js#L309) should but if you change
```
if (createNewIds) {
//node.z = RED.view.getWorkspace();
//node.id = getID();
node.id = n.id;
}
```
the imported names are correct.

It shouldn't be too hard to add this string to the output of the save function after the arduino stuff but the naming thing needs to be fixed first.

Is this something I should dig into or do you have plans for it?

[Forum post](https://forum.pjrc.com/threads/27807-Audio-Library-Tutorial?p=86114&viewfull=1#post86114)

**Comment by mamuesp** [comment]
After testing this should be closed.
