### ISSUE TITLE
GUI should require input or output object

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#92]
At least 1 input or output object is needed for the library to work.  The GUI allows export without any inputs or outputs, which produces a non-working result.

http://forum.pjrc.com/threads/26891-Problem-with-Audio-Peak-Object?p=56749&viewfull=1#post56749

**Comment by PaulStoffregen** [comment]
To be more precise, export must always have at least one node which implement "update responsibility".  Today, all the input and output objects do this, but no others do.  That'll probably continue to be true, due to the hardware-based nature of input and output.

Maybe the JSON node defs should have a field which specifies which objects implement update responsibility?

**Comment by mamuesp** [comment]
May be closed.
