### ISSUE TITLE
Add another ADC object which uses ADC1

### ISSUE THREAD

**Issue by PaulStoffregen** [PaulStoffregen/Audio#94]
This would allow stereo input using both ADC objects, or use of analogRead() on most pins, which are tied to ADC0 rather than ADC1.

**Comment by benguild** [comment]
I just spotted this issue being open after creating a thread about it. I poked around in the code but only noticed that changing the references to ADC0 to ADC1 as a test didn't work and seemed to crash the chip.

Are there any technical hardware limitations here to consider vs. the ability to process stereo audio on the 3.1+ board(s)?

**Comment by PaulStoffregen** [comment]
Yes, there are technical limitations, which are documented in the MK20DX256 reference manual.  Specifically, only certain pins work with ADC1.

**Comment by benguild** [comment]
Right, I remember reading that.
How much work is involved here? Can I help?

**Comment by benguild** [comment]
Please forgive my ignorance of the complexity of this library here, but, I'm trying to understand why changing ADC0 to ADC1 in the code doesn't work at least as a test. The chip is apparently able to handle ADC0/1 on that pin, but I'm not getting any input.

I don't see any reference to the ADCs in AudioStream or DMAChannel at first glance.

```
	// enable the ADC for hardware trigger and DMA
	ADC1_SC2 |= ADC_SC2_ADTRG | ADC_SC2_DMAEN;

	// set up a DMA channel to store the ADC data
	dma.begin(true);
	dma.TCD->SADDR = &ADC1_RA;
	dma.TCD->SOFF = 0;
	dma.TCD->ATTR = DMA_TCD_ATTR_SSIZE(1) | DMA_TCD_ATTR_DSIZE(1);
	dma.TCD->NBYTES_MLNO = 2;
	dma.TCD->SLAST = 0;
	dma.TCD->DADDR = analog_rx_buffer;
	dma.TCD->DOFF = 2;
	dma.TCD->CITER_ELINKNO = sizeof(analog_rx_buffer) / 2;
	dma.TCD->DLASTSGA = -sizeof(analog_rx_buffer);
	dma.TCD->BITER_ELINKNO = sizeof(analog_rx_buffer) / 2;
	dma.TCD->CSR = DMA_TCD_CSR_INTHALF | DMA_TCD_CSR_INTMAJOR;
	dma.triggerAtHardwareEvent(DMAMUX_SOURCE_ADC1);
	update_responsibility = update_setup();
	dma.enable();
	dma.attachInterrupt(isr);
```

... This compiles and runs but just doesn't do anything for me. Not sure what else is missing but I've been scouring libraries for clues out of personal interest.

**Comment by PaulStoffregen** [comment]
Maybe also configure ADC1 in the constructor?

**Comment by benguild** [comment]
Isn't that what I'm doing? Not sure which constructor you're talking about, but this is in init() of `input_adc.cpp` of course.

I noticed something about configuring the clock to the second ADC in @pedvide's code but it seems like that's handled by PDB0 here at first glance.

**Comment by pedvide** [comment]
I recommend that you do it anyway:
SIM_SCGC6 |= SIM_SCGC6_ADC0;
#if defined(__MK20DX256__)
SIM_SCGC3 |= SIM_SCGC3_ADC1;
#endif
If for whatever reason the clocks aren't running and you use the ADC, Teensy will crash.

**Comment by PaulStoffregen** [comment]
Might wanna use:

#if defined(__MK20DX256__)

**Comment by benguild** [comment]
@PaulStoffregen — how much code is really required here for this dual ADC/AnalogInput support? If it's a major rewrite, I didn't want to spend a lot of time on it right now.

However, I am interested in this functionality. Could we cooperate on it somehow?

**Comment by PaulStoffregen** [comment]
Ben, I'm currently working on another project at the moment.  I simply can't put the time into guiding your efforts or resolving these problems.

I will be working on the audio library again later this year.  Stereo ADC is on my TO-DO list.

If you want to work on this now, great.  It is open source.  But I can't help much.  I'm currently working on other stuff, and the very best way for me to make long-term progress on Audio is getting these other things done, so I can fully concentrate on the audio library again.

**Comment by benguild** [comment]
Got it, that makes sense. Maybe I can round up some of the other guys to
work on it together.

If we hit a roadblock I'll be sure to reach out for advice! Thanks for
letting us know

**Comment by PaulStoffregen** [comment]
fixed by https://github.com/PaulStoffregen/Audio/commit/d5bfe6c3ea554395e90bab178eabedb795984e6f

**Comment by benguild** [comment]
Thanks @PaulStoffregen!
